//
//  Oven.swift
//  MySampleApp
//
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.5
//

import Foundation
import UIKit
import AWSDynamoDB

class oven: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _id: String?
    var _name: String?
    var _description: String?
    var _instructions: String?
    var _userID: String?
    
    class func dynamoDBTableName() -> String {
        
        return "solarrecipes-mobilehub-623139932-Oven"
    }
    
    class func hashKeyAttribute() -> String {
        
        return "_id"
    }
    
    class func rangeKeyAttribute() -> String {
        
        return "_name"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
            "_id" : "id",
            "_name" : "name",
            "_description" : "description",
            "_instructions" : "instructions",
            "_userID" : "userID",
        ]
    }
}
